[package]
name = "reqwest-pretty-json"
version = "0.1.0"
authors = ["Cyril Plisko <cyril.plisko@mountall.com>"]
edition = "2018"
description = "Easy way to emit prettified JSON body in via reqwest::RequestBuilder"

[dependencies]
reqwest = "0.9"
serde = "1.0"
serde_json = "1.0"
